Tarea-2-BD/Pages/View/List/Employee.cshtml.cs
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics.Eventing.Reader;
using Tarea_2_BD.Pages.Model;
using static System.Runtime.InteropServices.JavaScript.JSType;


namespace Tarea_2_BD.Pages.View.List
{
    public class EmployeeModel : PageModel
    {
        public string errorMessage = "";
        public List<Empleado> listaEmpleados = new List<Empleado>();
        public ConnectSQL SQL = new ConnectSQL();
		public string Ip;
		public int whatFilter; // 0 = no hubo, 1=letras, 2=numeros 

		public string SuccessMessage { get; set; }



		public void OnGet(string username)
		{
            ViewData["ShowLogoutButton"] = true;
            Ip = HttpContext.Connection.RemoteIpAddress?.ToString();
			string user = (string)HttpContext.Session.GetString("Usuario");
			Console.WriteLine(user);

			DateTime dateNow = DateTime.Now;

			string busqueda = " ";

			using (SQL.connection)
            {


				int resultCode = ListarEmpleados(busqueda, user, Ip, dateNow);

				if (resultCode != 0)
				{
					errorMessage = SQL.BuscarError(resultCode);
				}

            }

        }

		


		//aqui estaran todos los metodos post 

		public IActionResult OnPostEditarEmpleado()
		{
            ViewData["ShowLogoutButton"] = true;
            string busqueda = Request.Form["Nombre"];
			HttpContext.Session.SetString("Empleado", busqueda);
			Console.WriteLine(busqueda);
			Console.WriteLine("editar");

            return RedirectToPage("/View/UDC/Editar");
        }
		public IActionResult OnPostBorrarEmpleado()
		{
            ViewData["ShowLogoutButton"] = true;
            string busqueda = Request.Form["Nombre"];
			HttpContext.Session.SetString("Empleado", busqueda);
			Console.WriteLine(busqueda);
			Console.WriteLine("borrar");
			return RedirectToPage("/View/UDC/Eliminar");
		}
		public IActionResult OnPostConsultarEmpleado()
		{
            ViewData["ShowLogoutButton"] = true;
            string busqueda = Request.Form["Nombre"];
			HttpContext.Session.SetString("Empleado", busqueda);
			Console.WriteLine(busqueda);
			Console.WriteLine("empleado");
			return RedirectToPage("/View/UDC/Consultar");
		}
		public IActionResult OnPostConsultarMovimientos()
		{
            ViewData["ShowLogoutButton"] = true;
            string busqueda = Request.Form["Nombre"];
			HttpContext.Session.SetString("Empleado", busqueda);
			Console.WriteLine(busqueda);
			Console.WriteLine("movimientos");
			return RedirectToPage("/View/List/Movimiento");
		}


		public int ListarEmpleados(string busqueda, string username, string ip,DateTime date)
		{
			SQL.Open();
			SQL.LoadSP("[dbo].[ListarEmpleados]");

			SQL.OutParameter("@OutResultCode", SqlDbType.Int, 0);

			SQL.InParameter("@InUsername", username, SqlDbType.VarChar);
			SQL.InParameter("@InIp", ip, SqlDbType.VarChar);
			SQL.InParameter("@InPostTime", date, SqlDbType.DateTime);


			if (string.IsNullOrWhiteSpace(busqueda))
			{
				SQL.InParameter("@InLetters", SqlDbType.VarChar); //se mandan los parametros nulos 
				SQL.InParameter("@InNumbers", SqlDbType.Int);
			}
			else
			{
				try //aqui verificamos si tratamos de buscar por valor doc id 
				{
					int number = int.Parse(busqueda);
					SQL.InParameter("@InLetters", SqlDbType.VarChar); //se mandan los parametros nulos 
					SQL.InParameter("@InNumbers", number, SqlDbType.Int);
				}
				catch //estamos buscando por nombre 
				{
					SQL.InParameter("@InLetters", busqueda, SqlDbType.VarChar); //se mandan los parametros nulos 
					SQL.InParameter("@InNumbers", SqlDbType.Int);
				}

			}

			//ya habiendo cargado los posibles parametros entonces podemos llamar al SP
			using (SqlDataReader dr = SQL.command.ExecuteReader())
			{
				int resultCode = 0;

				if (dr.Read()) //primero verificamos si el resultcode es positivo
				{
					resultCode = dr.GetInt32(0);

					if (resultCode == 0)
					{
						Console.WriteLine("Traida de datos exitosa");
					}
					else
					{
						SQL.Close();
						return resultCode;
					}

				}
				
				dr.NextResult(); //ya que leimos el outResultCode, leeremos los datos del dataser
				listaEmpleados = new List<Empleado>();
				while (dr.Read())
				{
					Empleado empleado = new Empleado();
					empleado.Puesto = dr.GetString(0);
					empleado.Nombre = dr.GetString(1);
					empleado.ValorDocumentoIdentidad = dr.GetInt32(2);
					empleado.FechaContratacion = dr.GetDateTime(3);
					empleado.SaldoVacaciones = (decimal)dr.GetSqlMoney(4);

					listaEmpleados.Add(empleado);
				}

				SQL.Close();
				return resultCode;
			}
		}


		public void OnPostFiltrarEmpleados()
        {
            ViewData["ShowLogoutButton"] = true;
            Ip = HttpContext.Connection.RemoteIpAddress?.ToString();
			DateTime dateNow = DateTime.Now;

			string busqueda = Request.Form["Filtrar"];
			string user = (string)HttpContext.Session.GetString("Usuario");



			using (SQL.connection)
			{
				
				

				int resultCode = ListarEmpleados(busqueda, user, Ip, dateNow);

                if (resultCode != 0)
                {
                    errorMessage = SQL.BuscarError(resultCode);
                }

			}


		}
	}
}

Tarea-2-BD/Pages/View/List/Movimiento.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;
using System.Reflection.PortableExecutable;
using Tarea_2_BD.Pages.Model;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Tarea_2_BD.Pages.View.List
{
    public class MovimientoModel : PageModel
    {

        public Empleado empleadoActual;
		public ConnectSQL SQL = new ConnectSQL();
		public List<Movimiento> listaMovimientos;
		public string errorMessage = "";
		public void OnGet()
        {
            ViewData["ShowLogoutButton"] = true;

            //Primero obtenemos el nombre del empleado 
            string empleado = (string)HttpContext.Session.GetString("Empleado");

			empleadoActual = new Empleado(); 
			empleadoActual.Nombre = empleado ;



			using (SQL.connection)
			{
				

				int resultCode = ListarMovimientos(empleado);

				if (resultCode != 0)
				{
					errorMessage = SQL.BuscarError(resultCode);
				}


				
			}			

		}


		public int ListarMovimientos(string nombreEmpleado)
		{
            ViewData["ShowLogoutButton"] = true;
            SQL.Open();
			SQL.LoadSP("[dbo].[ListarMovimientos]");

			SQL.OutParameter("@OutResultCode", SqlDbType.Int, 0);
			SQL.OutParameter("@OutValorDocumentoidentidad", SqlDbType.Int, 0);
			SQL.OutParameter("@OutSaldo", SqlDbType.Money, 0);

			SQL.InParameter("@InEmpleado", nombreEmpleado, SqlDbType.VarChar);



			//ya habiendo cargado los posibles parametros entonces podemos llamar al SP
			using (SqlDataReader dr = SQL.command.ExecuteReader())
			{
				int resultCode = 0;

				if (dr.Read()) //primero verificamos si el resultcode es positivo
				{
					resultCode = dr.GetInt32(0);

					if (resultCode == 0)
					{
						Console.WriteLine("Traida de movimientos");
					}
					else
					{
						Console.WriteLine("Error al llamar al SP");
						SQL.Close();
						return resultCode;
					}

				}

				dr.NextResult(); //ya que leimos el outResultCode, leeremos los datos del dataser
				if (dr.Read()) // Verifica si hay resultados para el saldo de vacaciones
				{
					empleadoActual.SaldoVacaciones = dr.GetDecimal(0); //sacamos el saldo de vacaciones
					Console.WriteLine(empleadoActual.SaldoVacaciones);
				}
					

				dr.NextResult();
				if (dr.Read())
				{
					empleadoActual.ValorDocumentoIdentidad = dr.GetInt32(0);
					Console.WriteLine(empleadoActual.ValorDocumentoIdentidad);
				}


				string saldo = empleadoActual.SaldoVacaciones.ToString();
				HttpContext.Session.SetString("Saldo", saldo);
				HttpContext.Session.SetInt32("DocId", empleadoActual.ValorDocumentoIdentidad);

				dr.NextResult();

				listaMovimientos = new List<Movimiento>();

				while (dr.Read())
				{
					Movimiento movimiento = new Movimiento();

					movimiento.Fecha = dr.GetDateTime(0);
					movimiento.Estampa = TimeOnly.FromTimeSpan(dr.GetTimeSpan(1));
					movimiento.tipoMovimiento = dr.GetString(2);
					movimiento.Monto = dr.GetDecimal(3);
					movimiento.NuevoSaldo = dr.GetDecimal(4);
					movimiento.NombreUsuario = dr.GetString(5);
					movimiento.ipAdress = dr.GetString(6);

					listaMovimientos.Add(movimiento);
				}

				SQL.Close();
				return resultCode;
			}
		}
	}
}

Tarea-2-BD/Pages/View/List/Employee.cshtml
@page
@model EmployeeModel
@{
	var successMessage = Model.SuccessMessage;
}


@if (Model.errorMessage.Length > 0)
{
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
		<strong>@Model.errorMessage</strong>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
	</div>
}


@if (!string.IsNullOrEmpty(successMessage))
{
	<div class="alert alert-success">
		@successMessage
	</div>
}
<br>
<h2>Lista de empleados</h2>

<form method="POST" asp-page-handler="FiltrarEmpleados">
	<div class="input-group">
		<input type="text" id="filtrar" name="Filtrar" class="form-control" placeholder="Ingrese filtro" />
		<div class="input-group-append">
			<button type="submit" class="btn btn-primary">Filtrar</button>
		</div>
	</div>
</form>

<br />
<div class="d-flex justify-content-between align-items-center">
	<a class="btn btn-primary" href="/view/Insert/empleado"> Insertar Empleado</a>
</div>

<br />


<table class="table">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Editar</th>
			<th>Borrar</th>
			<th>Consultar</th>
			<th>Movimientos</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.listaEmpleados)
		{
			<tr>
				<td>@item.Nombre</td>
				<td>
					<form method="post" asp-page-handler="EditarEmpleado">
						<input type="hidden" name="nombre" value="@item.Nombre" />
						<button type="submit" class="btn btn-primary">Editar</button>
					</form>
				</td>
				<td>
					<form method="post" asp-page-handler="BorrarEmpleado">
						<input type="hidden" name="nombre" value="@item.Nombre" />
						<button type="submit" class="btn btn-primary">Borrar</button>
					</form>
				</td>
				<td>
					<form method="post" asp-page-handler="ConsultarEmpleado">
						<input type="hidden" name="nombre" value="@item.Nombre" />
						<button type="submit" class="btn btn-primary">Consultar</button>
					</form>
				</td>
				<td>
					<form method="post" asp-page-handler="ConsultarMovimientos">
						<input type="hidden" name="nombre" value="@item.Nombre" />
						<button type="submit" class="btn btn-primary">Ver Movimientos</button>
					</form>
				</td>
			</tr>
		}
	</tbody>
</table>

Tarea-2-BD/Pages/View/List/Movimiento.cshtml
@page
@model Tarea_2_BD.Pages.View.List.MovimientoModel
@{
}


<h3>Empleado</h3>
<dl>
	<dt>Nombre:</dt>
	<dd>@Model.empleadoActual.Nombre</dd>

	<dt>Documento de Identidad:</dt>
	<dd>@Model.empleadoActual.ValorDocumentoIdentidad</dd>

	<dt>Saldo de Vacaciones:</dt>
	<dd>@Model.empleadoActual.SaldoVacaciones</dd>
</dl>




<br />
<div class="d-flex justify-content-between align-items-center">
	<h3>Movimientos</h3>
	<a class="btn btn-primary" href="/view/Insert/movement"> Insertar Movimiento</a>
</div>

<br />
<table class="table">
	<thead>
		<tr>
			<th>Fecha</th>
			<th>Estampa de Tiempo</th>
			<th>Tipo de Movimiento</th>
			<th>Monto</th>
			<th>Nuevo Saldo</th>
			<th>Username</th>
			<th>Ip</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.listaMovimientos)
		{
			<tr>
				<td>@item.Fecha</td>
				<td>@item.Estampa</td>
				<td>@item.tipoMovimiento</td>
				<td>@item.Monto</td>
				<td>@item.NuevoSaldo</td>
				<td>@item.NombreUsuario</td>
				<td>@item.ipAdress</td>
			</tr>
		}
	</tbody>
</table>


<div class="col-sm-3 d-grid">
	<a class="btn btn-primary" href="/View/List/Employee">Regresar</a>

</div>






	